services:
  - type: web
    name: commercehub-api
    runtime: docker
    dockerfilePath: src/CommerceHub.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_KEY
        sync: false
      - key: JWT_ISSUER
        value: CommerceHub
      - key: JWT_AUDIENCE
        value: CommerceHubClient
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: RABBITMQ_HOST
        sync: false
      - key: RABBITMQ_USER
        value: guest
      - key: RABBITMQ_PASS
        value: guest
      - key: REDIS_CONNECTION_STRING
        sync: false
      - key: IDENTITY_DB_CONNECTION
        sync: false
      - key: PRODUCT_DB_CONNECTION
        sync: false
      - key: ORDER_DB_CONNECTION
        sync: false
      - key: PAYMENT_DB_CONNECTION
        sync: false
      - key: VENDOR_DB_CONNECTION
        sync: false
      - key: INVENTORY_DB_CONNECTION
        sync: false
      - key: CMS_DB_CONNECTION
        sync: false
      - key: AI_DB_CONNECTION
        sync: false
      - key: ANALYTICS_DB_CONNECTION
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
