services:
  - type: web
    name: commercehub-api
    runtime: docker
    dockerfilePath: docker/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: "http://+:8080"
      - key: JWT_ISSUER
        value: CommerceHub
      - key: JWT_AUDIENCE
        value: CommerceHubClient
      - key: RABBITMQ_HOST
        sync: false
      - key: RABBITMQ_USER
        sync: false
      - key: RABBITMQ_PASS
        sync: false
      - key: RABBITMQ_VHOST
        sync: false
      - key: REDIS_CONNECTION_STRING
        sync: false
      - key: JWT_KEY
        sync: false
      - key: IDENTITY_DB_CONNECTION
        sync: false
      - key: PRODUCT_DB_CONNECTION
        sync: false
      - key: ORDER_DB_CONNECTION
        sync: false
      - key: PAYMENT_DB_CONNECTION
        sync: false
      - key: VENDOR_DB_CONNECTION
        sync: false
      - key: INVENTORY_DB_CONNECTION
        sync: false
      - key: CMS_DB_CONNECTION
        sync: false
      - key: AI_DB_CONNECTION
        sync: false
      - key: ANALYTICS_DB_CONNECTION
        sync: false
      - key: NOTIFICATION_DB_CONNECTION
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: Smtp__EnableSsl
        value: "true"
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: UPI_ID
        sync: false
      - key: UPI_MERCHANT_NAME
        value: CommerceHub
      - key: SEED__ENABLED
        value: "true"
      - key: SEED__ADMINEMAIL
        sync: false
      - key: SEED__ADMINPASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://commercehub-siranjeevis01.web.app,https://commerce-mobile-siranjeevis01.web.app,http://localhost:4200,http://localhost:8100"
    healthCheckPath: /health
    autoDeploy: true
