apiVersion: v1
kind: Secret
metadata:
  name: commercehub-secrets
type: Opaque
stringData:
  jwt-key: {{ .Values.jwtKey | default "${JWT_KEY}" }}
  jwt-issuer: {{ .Values.env.JWT_ISSUER | default "CommerceHub" }}
