apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "commercehub.fullname" . }}
  labels:
    {{- include "commercehub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "commercehub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "commercehub.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT }}
            - name: JWT_ISSUER
              value: {{ .Values.env.JWT_ISSUER }}
            - name: JWT_AUDIENCE
              value: {{ .Values.env.JWT_AUDIENCE }}
            {{- range .Values.envFromSecrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: commercehub-secrets
                  key: {{ . | lower }}
            {{- end }}
            {{- range .Values.envFromConfigMap }}
            - name: {{ . }}
              valueFrom:
                configMapKeyRef:
                  name: commercehub-config
                  key: {{ . | lower }}
            {{- end }}
          {{- include "commercehub.probes" . | nindent 10 }}
          {{- include "commercehub.resources" . | nindent 10 }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
